# noqa: N999
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create hierarchy table."""

from __future__ import annotations

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "1765980060"
down_revision = "1765979850"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabularies_hierarchy",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("parent_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("pid", sa.String(length=255), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("titles", sa.JSON(), nullable=False),
        sa.Column("ancestors", sa.JSON(), nullable=False),
        sa.Column("ancestors_or_self", sa.JSON(), nullable=False),
        sa.Column("leaf", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["vocabularies_metadata.id"],
            name=op.f("fk_vocabularies_hierarchy_id_vocabularies_metadata"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["vocabularies_hierarchy.id"],
            name=op.f("fk_vocabularies_hierarchy_parent_id_vocabularies_hierarchy"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabularies_hierarchy")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vocabularies_hierarchy")
    # ### end Alembic commands ###
