from mock_module_gen.resources.config import MockModuleGenResourceConfig
from mock_module_gen.resources.resource import MockModuleGenResource
from mock_module_gen.services.config import MockModuleGenServiceConfig
from mock_module_gen.services.service import MockModuleGenService

MOCK_MODULE_GEN_RESOURCE_CONFIG = MockModuleGenResourceConfig
MOCK_MODULE_GEN_RESOURCE_CLASS = MockModuleGenResource
MOCK_MODULE_GEN_SERVICE_CONFIG = MockModuleGenServiceConfig
MOCK_MODULE_GEN_SERVICE_CLASS = MockModuleGenService
