name: Build

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 12
        type: string

env:
  OAREPO_VERSION: ${{ inputs.oarepo }}
  INVENIO_ORCID_CLIENT_ID: ${{secrets.INVENIO_ORCID_CLIENT_ID}}
  INVENIO_ORCID_CLIENT_SECRET: ${{secrets.INVENIO_ORCID_CLIENT_SECRET}}
  INVENIO_OPENAIRE_CLIENT_ID: ${{secrets.INVENIO_OPENAIRE_CLIENT_ID}}
  INVENIO_OPENAIRE_CLIENT_SECRET: ${{secrets.INVENIO_OPENAIRE_CLIENT_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Show oarepo version
        run: |
          echo "OAREPO_VERSION: >>>$OAREPO_VERSION<<<"

      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Opensearch
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2
          plugins: analysis-icu

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Run tests
        run: |
          ./run-tests.sh

      - name: Freeze packages
        run: |
          pip freeze > requirements.txt

      - name: Build package to publish
        run: |
          pip install -U setuptools pip wheel
          python setup.py sdist bdist_wheel

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements.txt
          path: requirements.txt
