name: Manual test

on:
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 12
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
